@extends('layouts.app')
@section('title',$campaign->name.' analytics')
@section('content')
<div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><a href="{{ route('dashboard') }}">&larr; Dashboard</a><h1 class="h3 fw-bold mt-2">{{ $campaign->name }}</h1><p class="text-secondary">{{ $campaign->status->label() }} · {{ $from->toDateString() }} to {{ $to->toDateString() }}</p></div><div>@can('updateBudget',$campaign)<a class="btn btn-primary" href="{{ route('campaigns.budget.edit',$campaign) }}">Edit budget</a>@endcan</div></div>
@if($campaign->last_error)<div class="alert alert-danger">{{ $campaign->last_error }}</div>@endif
<div class="row g-3 mb-4">@foreach([['Budget',($campaign->budget?->currency_code.' '.$campaign->budget?->amount)],['Spend',$campaign->budget?->currency_code.' '.$metrics['spend']],['Impressions',number_format($metrics['impressions'])],['Daily reported reach',number_format($metrics['reach'])],['Clicks',number_format($metrics['clicks'])],['Results',number_format($metrics['results'])],['CPM',$metrics['cpm']??'—'],['CPC',$metrics['cpc']??'—'],['CTR',$metrics['ctr']??'—'],['Cost / result',$metrics['cost_per_result']??'—']] as [$label,$value])<div class="col-6 col-md-4 col-xl"><div class="card stat-card h-100"><div class="card-body"><div class="small text-secondary">{{ $label }}</div><div class="h5 mt-2">{{ $value }}</div></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-lg-8"><div class="card content-card"><div class="card-body"><h2 class="h5">Daily trend</h2>@if($campaign->dailyInsights->isEmpty())<p>No synchronized data yet.</p>@else<canvas id="campaignTrend"></canvas>@endif</div></div></div><div class="col-lg-4"><div class="card content-card mb-4"><div class="card-body"><h2 class="h5">Meta status</h2><dl><dt>Configured</dt><dd>{{ $campaign->configured_status??'Unavailable' }}</dd><dt>Effective</dt><dd>{{ $campaign->effective_status??'Unavailable' }}</dd><dt>Attribution</dt><dd>{{ $campaign->dailyInsights->pluck('attribution_setting')->filter()->last()??'Unavailable' }}</dd><dt>Last insights sync</dt><dd>{{ $campaign->dailyInsights->max('synced_at')?->diffForHumans()??'Never' }}</dd><dt>Remaining schedule</dt><dd>{{ $campaign->budget?->ends_at?->isFuture()?$campaign->budget->ends_at->diffForHumans():'No remaining scheduled period' }}</dd></dl></div></div><div class="card content-card"><div class="card-body"><h2 class="h5">Recommendations</h2><p class="small text-secondary">Rule-based guidance, not a guarantee.</p><ul>@forelse($recommendations as $item)<li>{{ $item }}</li>@empty<li>No recommendation for this period.</li>@endforelse</ul></div></div></div></div>
<div class="card content-card mt-4"><div class="card-body"><h2 class="h5">Metric explanations</h2><div class="row g-3 small">@foreach(['Impressions'=>'Times the ads appeared.','Reach'=>'People Meta reports reached for a period; daily reach is not summed.','Frequency'=>'Average times each reached person saw the ad.','CTR'=>'Clicks divided by impressions.','CPC'=>'Spend divided by clicks.','CPM'=>'Spend per 1,000 impressions.','Cost per result'=>'Spend divided by the primary result for this goal.'] as $term=>$explanation)<div class="col-md-6"><strong>{{ $term }}</strong>: {{ $explanation }}</div>@endforeach</div></div></div>
@if($campaign->dailyInsights->isNotEmpty())<script>document.addEventListener('DOMContentLoaded',()=>{const rows=@json($campaign->dailyInsights->map(fn($r)=>['date'=>$r->insight_date->toDateString(),'spend'=>$r->spend,'clicks'=>$r->clicks])->values());new Chart(document.getElementById('campaignTrend'),{type:'line',data:{labels:rows.map(r=>r.date),datasets:[{label:'Spend',data:rows.map(r=>r.spend),borderColor:'#0d6efd'},{label:'Clicks',data:rows.map(r=>r.clicks),borderColor:'#198754'}]}})});</script>@endif
@endsection
