@extends('layouts.app')
@section('title','Analytics dashboard')
@section('content')
<span class="visually-hidden">Active Campaigns · Recent campaigns</span>
<div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><h1 class="h3 fw-bold mb-1">Advertising analytics</h1><p class="text-secondary mb-0">Synchronized Meta performance for {{ $from->toDateString() }} to {{ $to->toDateString() }}.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('analytics.compare') }}">Compare campaigns</a>@can('manageAnalytics',$business)<a class="btn btn-outline-secondary" href="{{ route('analytics.backfill.create') }}">Sync history</a>@endcan</div></div>
<form class="card content-card mb-4"><div class="card-body row g-3 align-items-end"><div class="col-md-3"><label class="form-label">From</label><input class="form-control" type="date" name="date_from" value="{{ $from->toDateString() }}"></div><div class="col-md-3"><label class="form-label">To</label><input class="form-control" type="date" name="date_to" value="{{ $to->toDateString() }}"></div><div class="col-md-2"><label class="form-label">Goal</label><select class="form-select" name="goal"><option value="">All goals</option>@foreach(config('ads.goals') as $key=>$goal)<option value="{{ $key }}" @selected(request('goal')===$key)>{{ $goal['label'] }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All statuses</option>@foreach(\App\Enums\AdCampaignStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">Apply</button></div></div></form>
@forelse($byCurrency as $currency=>$totals)<div class="mb-4"><div class="small text-secondary mb-2">Currency: {{ $currency }}</div><div class="row g-3">@foreach([['Total spend',$currency.' '.$totals['spend']],['Impressions',number_format($totals['impressions'])],['Daily reported reach',number_format($totals['reach'])],['Clicks',number_format($totals['clicks'])],['Results',number_format($totals['results'])],['Cost per result',$totals['cost_per_result']?$currency.' '.$totals['cost_per_result']:'—'],['Active campaigns',$campaigns->where('status',\App\Enums\AdCampaignStatus::Active)->count()]] as [$label,$value])<div class="col-6 col-lg"><div class="card stat-card h-100"><div class="card-body"><div class="stat-label">{{ $label }}</div><div class="h4 mt-2 mb-0">{{ $value }}</div></div></div></div>@endforeach</div></div>@empty<div class="alert alert-light border">No synchronized data yet. Start the queue worker or request a historical synchronization.</div>@endforelse
@if($rows->isNotEmpty())<div class="row g-4 mb-4"><div class="col-lg-6"><div class="card content-card"><div class="card-body"><h2 class="h5">Spend over time</h2><canvas id="spendChart"></canvas></div></div></div><div class="col-lg-6"><div class="card content-card"><div class="card-body"><h2 class="h5">Results over time</h2><canvas id="resultsChart"></canvas></div></div></div></div>@endif
<div class="card content-card"><div class="card-header bg-white p-4 d-flex justify-content-between"><div><h2 class="h5 mb-1">Campaign performance</h2><div class="small text-secondary">Last synchronized: {{ $lastSynced?->diffForHumans() ?? 'Never' }}</div></div><a href="{{ route('analytics.export',['type'=>'campaign-performance']+request()->query()) }}">Export CSV</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Campaign</th><th>Status</th><th>Currency</th><th>Spend</th><th>Impressions</th><th>Clicks</th><th>Results</th><th>CTR</th></tr></thead><tbody>@forelse($campaigns as $campaign)@php($m=$campaignMetrics[$campaign->id])<tr><td><a href="{{ route('campaigns.analytics',$campaign) }}">{{ $campaign->name }}</a></td><td>{{ $campaign->status->label() }}</td><td>{{ $campaign->budget?->currency_code }}</td><td>{{ $m['spend'] }}</td><td>{{ number_format($m['impressions']) }}</td><td>{{ number_format($m['clicks']) }}</td><td>{{ number_format($m['results']) }}</td><td>{{ $m['ctr'] ?? '—' }}</td></tr>@empty<tr><td colspan="8">No campaigns match these filters.</td></tr>@endforelse</tbody></table></div></div>
@if($rows->isNotEmpty())<script>document.addEventListener('DOMContentLoaded',()=>{const rows=@json($rows->map(fn($r)=>['date'=>$r->insight_date->toDateString(),'spend'=>$r->spend,'results'=>$r->landing_page_views??$r->leads??$r->messaging_conversations_started])->values());const labels=[...new Set(rows.map(r=>r.date))];const make=(id,key,label,color)=>new Chart(document.getElementById(id),{type:'line',data:{labels,datasets:[{label,data:labels.map(d=>rows.filter(r=>r.date===d).reduce((s,r)=>s+Number(r[key]),0)),borderColor:color,tension:.3}]},options:{responsive:true}});make('spendChart','spend','Spend','#0d6efd');make('resultsChart','results','Results','#198754')});</script>@endif
@endsection
