@extends('layouts.app')
@section('title','Ad Spend')
@section('content')
<div class="d-flex justify-content-between mb-4"><div><h1 class="h3 fw-bold">Ad Spend</h1><p class="text-secondary">Current-month information synchronized from Meta.</p></div>@can('manageAnalytics',$business)<a class="btn btn-outline-primary" href="{{ route('spending-controls.edit') }}">Spending controls</a>@endcan</div>
<div class="alert alert-info">Advertising charges are billed directly by Meta. This application displays information returned by Meta and does not hold your advertising balance or card details.</div>
@if($rows->isEmpty())<div class="alert alert-light border">No synchronized data yet.</div>@else<div class="card content-card"><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Campaign</th><th>Goal</th><th>Currency</th><th>Spend</th><th>Budget</th></tr></thead><tbody>@foreach($rows as $row)<tr><td>{{ $row->insight_date->toDateString() }}</td><td>{{ $row->campaign->name }}</td><td>{{ $row->campaign->goal->label() }}</td><td>{{ $row->currency_code }}</td><td>{{ $row->spend }}</td><td>{{ $row->campaign->budget?->amount }}</td></tr>@endforeach</tbody></table></div></div>@endif
@if($business->spendingControl)<div class="alert alert-warning mt-4">Business warning threshold: {{ $business->spendingControl->currency_code }} {{ $business->spendingControl->monthly_warning_amount??'Not set' }}. These local controls only prevent actions made through this application and do not replace Meta account spending limits.</div>@endif
@if($business->selectedMetaAdAccount?->latestSnapshot)<div class="card content-card mt-4"><div class="card-body"><h2 class="h5">Meta account snapshot</h2><p>Status: {{ $business->selectedMetaAdAccount->latestSnapshot->account_status??'Unavailable' }} · Spend cap: {{ $business->selectedMetaAdAccount->latestSnapshot->spend_cap??'Unavailable' }} · Updated {{ $business->selectedMetaAdAccount->latestSnapshot->snapshot_at->diffForHumans() }}</p></div></div>@endif
@endsection
