@extends('layouts.app')
@section('title', 'Select audience')
@section('content')
@php($activeStep = 4)
@php($audience = $campaign->audience)
@php($oldCountries = implode(', ', (array) old('countries', $audience?->countries ?? [])))
@php($oldStates = implode(', ', (array) old('states', $audience?->states ?? [])))
@php($oldCities = implode(', ', (array) old('cities', $audience?->cities ?? [])))
@php($oldInterests = collect(old('interests', $audience?->interests ?? []))->map(fn ($interest) => is_array($interest) ? ($interest['name'] ?? '') : $interest)->filter()->implode(', '))
<div class="mx-auto wizard-container">
    <div class="d-flex justify-content-between mb-3"><div><h1 class="h3 fw-bold mb-1">Select your audience</h1><p class="text-secondary mb-0">Start simple, then add optional targeting details.</p></div><a href="{{ route('campaigns.index') }}" class="btn btn-outline-secondary btn-sm align-self-start">Save & leave</a></div>
    @include('campaigns.partials.wizard-nav')
    <form method="POST" action="{{ route('campaigns.wizard.audience.update',$campaign) }}">@csrf @method('PUT')
    <div class="card content-card"><div class="card-body p-4 row g-4">
        <div class="col-12 col-md-6"><label for="location_type" class="form-label fw-semibold">Location type</label><select class="form-select" id="location_type" name="location_type"><option value="country" {{ old('location_type',$audience?->location_type?->value)==='country'?'selected':'' }}>Country</option><option value="state" {{ old('location_type',$audience?->location_type?->value)==='state'?'selected':'' }}>State</option><option value="city" {{ old('location_type',$audience?->location_type?->value)==='city'?'selected':'' }}>City</option><option value="radius" {{ old('location_type',$audience?->location_type?->value)==='radius'?'selected':'' }}>Radius around a point</option></select></div>
        <div class="col-12 location-field" data-location="country"><label class="form-label fw-semibold" for="countries">Countries</label><input class="form-control" id="countries" name="countries" value="{{ $oldCountries }}" placeholder="India, United States"><div class="form-text">Separate multiple locations with commas.</div></div>
        <div class="col-12 location-field" data-location="state"><label class="form-label fw-semibold" for="states">States</label><input class="form-control" id="states" name="states" value="{{ $oldStates }}" placeholder="Maharashtra, Karnataka"></div>
        <div class="col-12 location-field" data-location="city"><label class="form-label fw-semibold" for="cities">Cities</label><input class="form-control" id="cities" name="cities" value="{{ $oldCities }}" placeholder="Mumbai, Pune"></div>
        <div class="col-12 location-field" data-location="radius"><div class="row g-3"><div class="col-md-4"><label class="form-label" for="latitude">Latitude</label><input type="number" step="0.0000001" class="form-control" id="latitude" name="latitude" value="{{ old('latitude',$audience?->latitude) }}"></div><div class="col-md-4"><label class="form-label" for="longitude">Longitude</label><input type="number" step="0.0000001" class="form-control" id="longitude" name="longitude" value="{{ old('longitude',$audience?->longitude) }}"></div><div class="col-md-2"><label class="form-label" for="radius">Radius</label><input type="number" class="form-control" id="radius" name="radius" min="{{ config('ads.radius.min') }}" max="{{ config('ads.radius.max') }}" value="{{ old('radius',$audience?->radius) }}"></div><div class="col-md-2"><label class="form-label" for="radius_unit">Unit</label><select class="form-select" id="radius_unit" name="radius_unit"><option value="kilometer">km</option><option value="mile" {{ old('radius_unit',$audience?->radius_unit)==='mile'?'selected':'' }}>mile</option></select></div></div></div>
        <div class="col-6"><label class="form-label fw-semibold" for="age_min">Minimum age</label><input type="number" min="18" max="65" class="form-control" id="age_min" name="age_min" value="{{ old('age_min',$audience?->age_min ?? 18) }}"></div><div class="col-6"><label class="form-label fw-semibold" for="age_max">Maximum age</label><input type="number" min="18" max="65" class="form-control" id="age_max" name="age_max" value="{{ old('age_max',$audience?->age_max ?? 65) }}"></div>
        <div class="col-12"><label class="form-label fw-semibold">Gender</label><div class="d-flex flex-wrap gap-3">@foreach(config('ads.genders') as $gender)<label><input class="form-check-input me-1" type="checkbox" name="genders[]" value="{{ $gender }}" {{ in_array($gender,old('genders',$audience?->genders ?? ['all']))?'checked':'' }}> {{ str($gender)->title() }}</label>@endforeach</div></div>
        <div class="col-12"><label class="form-label fw-semibold" for="interests">Advanced: interests</label><input class="form-control" id="interests" name="interests" value="{{ $oldInterests }}" placeholder="Coffee, Fitness, Local shopping"><div class="form-text text-warning-emphasis">Draft placeholders only. These interests require validation against Meta before publishing.</div></div>
        <div class="col-12"><div class="form-check form-switch"><input type="checkbox" class="form-check-input" role="switch" id="advantage_audience" name="advantage_audience" value="1" {{ old('advantage_audience',$audience?->advantage_audience ?? true)?'checked':'' }}><label class="form-check-label fw-semibold" for="advantage_audience">Let Meta find the best audience</label></div></div>
    </div><div class="card-footer bg-white d-flex justify-content-between p-4"><a href="{{ route('campaigns.wizard.creative.edit',$campaign) }}" class="btn btn-outline-secondary">Back</a><button class="btn btn-primary">Save & continue</button></div></div></form>
</div>
<script>(()=>{const type=document.getElementById('location_type'),refresh=()=>document.querySelectorAll('.location-field').forEach(x=>x.hidden=x.dataset.location!==type.value);type.addEventListener('change',refresh);refresh();})();</script>
@endsection
