@extends('layouts.app')
@section('title', 'Create advertisement')
@section('content')
@php($activeStep = 3)
@php($creative = $campaign->creative)
<div class="mx-auto wizard-container-wide">
    <div class="d-flex justify-content-between mb-3"><div><h1 class="h3 fw-bold mb-1">Create your advertisement</h1><p class="text-secondary mb-0">Write the message and add one image or video.</p></div><a href="{{ route('campaigns.index') }}" class="btn btn-outline-secondary btn-sm align-self-start">Save & leave</a></div>
    @include('campaigns.partials.wizard-nav')
    <form method="POST" enctype="multipart/form-data" action="{{ route('campaigns.wizard.creative.update', $campaign) }}" id="creativeForm">@csrf @method('PUT')
    <div class="row g-4"><div class="col-12 col-xl-6"><div class="card content-card"><div class="card-body p-4 row g-3">
        <div class="col-12"><label class="form-label fw-semibold" for="format">Format</label><select class="form-select" name="format" id="format"><option value="single_image" {{ old('format',$creative?->format?->value)==='single_image'?'selected':'' }}>Single image</option><option value="single_video" {{ old('format',$creative?->format?->value)==='single_video'?'selected':'' }}>Single video</option></select></div>
        <div class="col-12"><label class="form-label fw-semibold" for="primary_text">Primary text</label><textarea class="form-control preview-input" id="primary_text" name="primary_text" maxlength="1250" rows="5" required>{{ old('primary_text',$creative?->primary_text) }}</textarea><div class="form-text">Up to 1,250 characters.</div></div>
        <div class="col-12"><label class="form-label fw-semibold" for="headline">Headline</label><input class="form-control preview-input" id="headline" name="headline" maxlength="255" value="{{ old('headline',$creative?->headline) }}"></div>
        <div class="col-12"><label class="form-label fw-semibold" for="description">Description</label><textarea class="form-control preview-input" id="description" name="description" maxlength="500" rows="2">{{ old('description',$creative?->description) }}</textarea></div>
        <div class="col-12"><label class="form-label fw-semibold" for="call_to_action">Call to action</label><select class="form-select" name="call_to_action" id="call_to_action">@foreach($ctas as $cta)<option value="{{ $cta }}" {{ old('call_to_action',$creative?->call_to_action)===$cta?'selected':'' }}>{{ str($cta)->replace('_',' ')->title() }}</option>@endforeach</select></div>
        @if($campaign->goal === \App\Enums\AdCampaignGoal::WebsiteTraffic)<div class="col-12"><label class="form-label fw-semibold" for="destination_url">Website URL</label><input type="url" class="form-control" id="destination_url" name="destination_url" value="{{ old('destination_url',$creative?->destination_url) }}" placeholder="https://example.com" required></div>@endif
        @if($campaign->goal === \App\Enums\AdCampaignGoal::LeadGeneration)
            <div class="col-12"><label class="form-label fw-semibold" for="lead_form_name">Lead form name</label><input class="form-control" id="lead_form_name" name="lead_form_name" value="{{ old('lead_form_name',$creative?->lead_form_name) }}" required></div>
            <div class="col-12"><label class="form-label fw-semibold" for="privacy_policy_url">Privacy policy URL</label><input type="url" class="form-control" id="privacy_policy_url" name="privacy_policy_url" value="{{ old('privacy_policy_url',$creative?->privacy_policy_url) }}" placeholder="https://example.com/privacy" required></div>
            <div class="col-12"><label class="form-label fw-semibold" for="privacy_policy_link_text">Privacy policy link text</label><input class="form-control" id="privacy_policy_link_text" name="privacy_policy_link_text" value="{{ old('privacy_policy_link_text',$creative?->privacy_policy_link_text ?: 'View privacy policy') }}" required></div>
            <div class="col-12"><label class="form-label fw-semibold">Customer fields</label><div class="d-flex flex-wrap gap-3">@foreach(['FULL_NAME'=>'Full name','EMAIL'=>'Email','PHONE'=>'Phone'] as $field=>$label)<label><input class="form-check-input me-1" type="checkbox" name="requested_fields[]" value="{{ $field }}" {{ in_array($field,old('requested_fields',$creative?->requested_fields ?? ['FULL_NAME','EMAIL']))?'checked':'' }}> {{ $label }}</label>@endforeach</div></div>
            <div class="col-md-6"><label class="form-label fw-semibold" for="completion_title">Completion title</label><input class="form-control" id="completion_title" name="completion_title" value="{{ old('completion_title',$creative?->completion_title ?: 'Thank you') }}" required></div>
            <div class="col-md-6"><label class="form-label fw-semibold" for="completion_button_text">Button text</label><input class="form-control" id="completion_button_text" name="completion_button_text" value="{{ old('completion_button_text',$creative?->completion_button_text ?: 'Visit website') }}" required></div>
            <div class="col-12"><label class="form-label fw-semibold" for="completion_message">Completion message</label><textarea class="form-control" id="completion_message" name="completion_message" rows="2" required>{{ old('completion_message',$creative?->completion_message ?: 'We received your details and will contact you soon.') }}</textarea></div>
            <div class="col-12"><label class="form-label fw-semibold" for="completion_destination_url">Completion destination URL <span class="text-secondary fw-normal">(optional)</span></label><input type="url" class="form-control" id="completion_destination_url" name="completion_destination_url" value="{{ old('completion_destination_url',$creative?->completion_destination_url) }}"></div>
        @endif
        @if($campaign->goal === \App\Enums\AdCampaignGoal::WhatsAppMessages)<div class="col-12"><label class="form-label fw-semibold" for="whatsapp_number">WhatsApp number</label><input class="form-control" id="whatsapp_number" name="whatsapp_number" value="{{ old('whatsapp_number',$creative?->whatsapp_number) }}" placeholder="+919876543210" required></div>@endif
        <div class="col-12"><label class="form-label fw-semibold" for="media">Media {{ $creative ? '(leave blank to keep current media)' : '' }}</label><input type="file" class="form-control" id="media" name="media" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,video/webm" {{ $creative ? '' : 'required' }}><div class="form-text">Images: JPG, PNG, WebP up to 10 MB. Videos: MP4, MOV, WebM up to 100 MB.</div></div>
    </div><div class="card-footer bg-white d-flex justify-content-between p-4"><a href="{{ route('campaigns.wizard.assets.edit',$campaign) }}" class="btn btn-outline-secondary">Back</a><button class="btn btn-primary">Save & continue</button></div></div></div>
    <div class="col-12 col-xl-6"><div class="card content-card sticky-xl-top" style="top:1rem"><div class="card-body p-4"><div class="d-flex gap-2 mb-3"><button type="button" class="btn btn-sm btn-primary preview-tab" data-preview="facebook">Facebook Feed</button><button type="button" class="btn btn-sm btn-outline-primary preview-tab" data-preview="instagram">Instagram Feed</button><button type="button" class="btn btn-sm btn-outline-primary preview-tab" data-preview="story">Instagram Story</button></div><div class="ad-preview" id="adPreview"><div class="p-3 fw-semibold" id="previewAccount" data-page="{{ $campaign->metaPage?->name ?: 'Facebook Page' }}" data-instagram="{{ $campaign->metaInstagramAccount?->username ? '@'.$campaign->metaInstagramAccount->username : 'Instagram account' }}">{{ $campaign->metaPage?->name ?: 'Facebook Page' }}</div><div class="px-3 pb-3" id="previewText">{{ $creative?->primary_text ?: 'Your advertisement text appears here.' }}</div><div class="preview-media" id="previewMedia">@if($creative)<img src="{{ route('campaigns.media.show',$campaign) }}" alt="Current creative media">@else<span>Add media to preview it</span>@endif</div><div class="p-3 border-top"><div class="fw-bold" id="previewHeadline">{{ $creative?->headline ?: 'Your headline' }}</div><div class="small text-secondary" id="previewDescription">{{ $creative?->description }}</div><button type="button" class="btn btn-light btn-sm mt-2 w-100" id="previewCta">{{ str($creative?->call_to_action ?: $ctas[0])->replace('_',' ')->title() }}</button></div></div><p class="small text-secondary mt-3 mb-0">Final appearance may vary after Meta processes the advertisement.</p></div></div></div></div>
    </form>
</div>
<script>(()=>{const val=id=>document.getElementById(id),map={primary_text:'previewText',headline:'previewHeadline',description:'previewDescription'};Object.entries(map).forEach(([input,output])=>val(input).addEventListener('input',()=>val(output).textContent=val(input).value));val('call_to_action').addEventListener('change',()=>val('previewCta').textContent=val('call_to_action').selectedOptions[0].text);val('media').addEventListener('change',()=>{const file=val('media').files[0];if(!file)return;const url=URL.createObjectURL(file),el=file.type.startsWith('video/')?document.createElement('video'):document.createElement('img');el.src=url;if(el.tagName==='VIDEO')el.controls=true;val('previewMedia').replaceChildren(el);});document.querySelectorAll('.preview-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.preview-tab').forEach(x=>x.className='btn btn-sm btn-outline-primary preview-tab');btn.className='btn btn-sm btn-primary preview-tab';val('adPreview').className='ad-preview '+btn.dataset.preview;val('previewAccount').textContent=btn.dataset.preview==='facebook'?val('previewAccount').dataset.page:val('previewAccount').dataset.instagram;}));})();</script>
@endsection
