@extends('layouts.app')
@section('title', 'Review campaign')
@section('content')
<div class="mx-auto wizard-container-wide"><div class="d-flex justify-content-between mb-4"><div><h1 class="h3 fw-bold mb-1">Review your advertisement</h1><p class="text-secondary mb-0">Nothing will be sent to Meta in this phase.</p></div><a href="{{ route('campaigns.index') }}" class="btn btn-outline-secondary align-self-start">Save as draft</a></div>
<div class="row g-4"><div class="col-12 col-xl-7">
@foreach([['Goal & name','campaigns.wizard.goal.edit'],['Meta assets','campaigns.wizard.assets.edit'],['Creative','campaigns.wizard.creative.edit'],['Audience','campaigns.wizard.audience.edit'],['Budget & schedule','campaigns.wizard.budget.edit']] as [$section,$routeName])<div class="card content-card mb-3"><div class="card-header bg-white border-0 d-flex justify-content-between p-4 pb-2"><h2 class="h5 mb-0">{{ $section }}</h2><a href="{{ route($routeName,$campaign) }}">Edit</a></div><div class="card-body px-4 pt-2">
@if($section==='Goal & name')<strong>{{ $campaign->name }}</strong><div class="text-secondary">{{ $campaign->goal->label() }}</div>
@elseif($section==='Meta assets')<div>{{ $campaign->metaAdAccount->name }}</div><div>{{ $campaign->metaPage->name }}</div><div class="text-secondary">{{ $campaign->metaInstagramAccount?->username ? '@'.$campaign->metaInstagramAccount->username : 'No Instagram account' }}</div>
@elseif($section==='Creative')<p>{{ $campaign->creative->primary_text }}</p><div class="preview-media rounded">@if(str_starts_with($campaign->creative->mime_type ?? '','video/'))<video src="{{ route('campaigns.media.show',$campaign) }}" controls></video>@else<img src="{{ route('campaigns.media.show',$campaign) }}" alt="Creative preview">@endif</div><div class="small text-secondary mt-2">Final appearance may vary after Meta processes the advertisement.</div>
@elseif($section==='Audience')<div>Ages {{ $campaign->audience->age_min }}–{{ $campaign->audience->age_max }} · {{ str($campaign->audience->location_type->value)->title() }}</div><div class="text-secondary">{{ $campaign->audience->advantage_audience?'Let Meta find the best audience':'Manual targeting' }}</div>
@else<div class="fs-4 fw-bold">{{ $campaign->budget->currency_code }} {{ number_format((float)$campaign->budget->amount,2) }} {{ $campaign->budget->budget_type->value }}</div><div>{{ $campaign->budget->starts_at->setTimezone($campaign->metaAdAccount->timezone_name ?: 'UTC')->format('M j, Y g:i A') }} – {{ $campaign->budget->ends_at?->setTimezone($campaign->metaAdAccount->timezone_name ?: 'UTC')->format('M j, Y g:i A') ?: 'No end date' }}</div><div class="text-secondary">{{ $campaign->metaAdAccount->timezone_name ?: 'UTC' }} · Estimated total: {{ $campaign->estimatedTotalBudget() ? $campaign->budget->currency_code.' '.$campaign->estimatedTotalBudget() : 'Depends on end date' }}</div>@endif
</div></div>@endforeach</div>
<div class="col-12 col-xl-5"><div class="card content-card sticky-xl-top" style="top:1rem"><div class="card-body p-4"><h2 class="h5">Ready for the next phase?</h2>@if($campaign->status === \App\Enums\AdCampaignStatus::Ready)<p class="text-secondary">The local review is complete. Continue to the final Meta preflight and confirmations.</p>@can('publish',$campaign)<a class="btn btn-primary w-100" href="{{ route('campaigns.publish.confirm',$campaign) }}">Review &amp; publish to Meta</a>@endcan @else<p class="text-secondary">This checks every section and marks the local draft ready. It does not publish anything.</p>@can('publish',$campaign)<form method="POST" action="{{ route('campaigns.mark-ready',$campaign) }}">@csrf<button class="btn btn-success w-100">Mark Ready for Publishing</button></form>@else<div class="alert alert-light border mb-0">Only an owner or admin can mark this campaign ready.</div>@endcan @endif</div></div></div></div></div>
@endsection
